Repository CSI-SCT-SB/CSL_201_Data_structure_Lab, pull requests merged in 2022-10, with the labels that each got.

#1 Add files via upload
  CSL203Syllabus.pdf
Labels: hacktoberfest-accepted

#2 _9.Binarysearchtree.c
  _5.LinkedListOperations
  _7.polynomialusinglinkedlist.c
  _9.binarysearchtree.c
Labels: good first issue, hacktoberfest-accepted

#6 Infix to postfix
  _11.a_Bubblesort.c
  _3.a_Infix to postfix.c
Labels: hacktoberfest-accepted

#7 Add files via upload
  README.md
  matmul.java
Labels: enhancement, hacktoberfest-accepted

#5 Add files via upload
  _11 (vii) mergesort.c
  _11(b)bubblesort.c
  _11(i)binarysort.c
  _11(iv)heapsort.c
  _11(vi)quicksort.c
  _11.(iii)insertionsort.c
Labels: good first issue, hacktoberfest-accepted

#8 Revert "Add files via upload"
  README.md
  matmul.java
Labels: bug

#9 Data Sructures Lab Program Codes
  _10.QueueUsingLL.c
  _10.StackUsingLL.c
  _6.aStackUsingArrays.c
  _6.b.CircularQueueUsingArrays.c
  _6.b.QueueUsingArrays.c
  _8.PalindromeStringCheck_DLL.c
Labels: hacktoberfest-accepted

#10 Infix to prefix
  _3.b_infix_to_prefix.c
Labels: hacktoberfest-accepted

#11 DS lab syllabus
  Data Structures Lab Syllabus.pdf
Labels: good first issue, hacktoberfest-accepted

#12 11 (ii) selectionsort
  _11.(ii)selectionsort.c
Labels: hacktoberfest-accepted

#13 Create _5ex.DoublyLinkedList.c
  _5ex.DoublyLinkedList.c
Labels: hacktoberfest-accepted

#15 added linear search and binary search
  _12.a.linearsearch.c
  _12.b.binarysearch.c
Labels: hacktoberfest-accepted

#16 _14.bfsdfs.c
  _14.bfsdfs.c
  _8.binarytreell.c
Labels: hacktoberfest-accepted

#17 _4.binarytreell.c
  _4.binarytreell.c
Labels: hacktoberfest-accepted

#18 Add files via upload
  Binary_Tree_Traversals_and_finding_height.c
Labels: hacktoberfest-accepted

#19 Add files via upload
  firstfitalloc.c
Labels: hacktoberfest-accepted

#20 Added Experiment 16b
  _16b.WorstFit.c
  _16c.BestFit.c
Labels: hacktoberfest-accepted
